Read Project structure for hear this directories
mseag/bible-karaoke pull request #150
Opened 2021-03-30 03:18 UTC by nh758

Reads HearThis project structures (from the HearThis directory), so that it can be used by hearThisImport.
Based on `/public/sources/hear-this.js`

2021-05-14 10:12 UTC, irahopkinson requested changes
Nice job on converting this to TS. I've added a few comments on things to fix up, but do use your discretion on which are necessary.

2021-05-17 06:07 UTC, nh758 commented on public/cli/lib/import/hearThis/readStructure.ts
> +    console.error(error);
Ok, I removed the try catch. I remember last time we had discussed letting the higher level functions catch errors. But let me know if there is a better way to do it.

2021-05-17 06:09 UTC, nh758 commented on public/cli/lib/import/hearThis/readStructure.ts
> +
I did not change anything here, as I'm not sure how to go about it. If this is what we want, I can look at it later.

2021-05-17 06:11 UTC, nh758 commented
Thanks Ira! I've made most of the changes requested. See a couple responses above and let me know if I should change anything else.

2021-05-17 09:08 UTC, irahopkinson commented on public/cli/lib/import/hearThis/readStructure.ts
> +export function getProjectStructure(rootDirectories: Array<string> = []) {
Great, you fixed the argument type but didn't add the return type. Sorry, I should have separated these 2 comments since there was 2 things to do.

2021-05-17 09:10 UTC, irahopkinson commented on public/cli/lib/import/hearThis/readStructure.ts
> +export function getProjectStructure(rootDirectories: Array<string> = []) {
I've fixed it myself since its the last thing and simplified the returned item to use the simpler syntax.

2021-05-17 09:17 UTC, irahopkinson approved these changes
👍 LGTM

2021-05-17 09:18 UTC, merged